server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /cart/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: login-authentication
          uri: lb://login-authentication
          predicates:
            - Path=/login,/signup,/logout,/adminSignup,/activeDefaultAccount
        - id: payment-order-service
          uri: lb://payment-order-service
          predicates:
            - Path=/payment/**,/order/**