server:
  port: ${PORT:9003}

spring:
  application:
    name: product-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 20MB
  data:
    mongodb:
      uri: ${MONGODB_URL}
#        host: localhost
#        port: 27017
#        database: ecommerce

eureka:
  instance:
    hostname: ${APPDOMAIN:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://127.0.0.1:8761/eureka/}

jwt:
  secret: "asdfghjkikjuhygfrd"

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:AKIATHQTSD2T7KRLYPHR}
      secret-key: ${AWS_SECRET_KEY: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}
    region:
      static: ${AWS_REGION_STATIC:ap-south-1}
    stack:
      auto: false

aws:
  s3:
    bucket: ${AWS_BUCKET_NAME:ecommerce-image-bucket1}

allowed:
  origin: ${REACT_APP_URL:http://localhost:3000}