server:
  port: ${PORT:9005}

spring:
  application:
    name: payment-order-service
  data:
    mongodb:
      uri: ${MONGODB_URL}
#      host: localhost
#      port: 27017
#      database: ecommerce

eureka:
  instance:
    hostname: ${APPDOMAIN:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://127.0.0.1:8761/eureka/}

jwt:
  secret: "asdfghjkikjuhygfrd"


razorPay:
  key: ${RAZORPAY_KEY:rzp_test_XZmE9htlGHPrr3}
  secret: ${RAZORPAY_SECRET:uOeBhzaxVD0LwctitTtF4JfG}

Feign:
  User_url: ${USER_SERVICE_URL:http://user-service/}
  Product_url: ${PRODUCT_SRVICE_URL:http://product-service/}

allowed:
  origin: ${REACT_APP_URL:http://localhost:3000}