server:
  port: ${PORT:8080}

eureka:
  instance:
#    prefer-ip-address: true
    hostname: ${APPDOMAIN:localhost}
  client:
    serviceUrl:
      defaultZone: Eurekaserver-env-2.eba-fipchgfv.us-east-1.elasticbeanstalk.com/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${REACT_APP_URL:http://localhost:3000}
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://Userservice-env.eba-kguuzuph.us-east-1.elasticbeanstalk.com
          predicates:
            - Path=/users/**, /cart/**
        - id: product-service
          uri: http://Productservice-env.eba-9x22mgz2.us-east-1.elasticbeanstalk.com
          predicates:
            - Path=/product/**
        - id: login-authentication
          uri: http://Loginservice-env.eba-kryhew59.us-east-1.elasticbeanstalk.com
          predicates:
            - Path=/login,/signup,/logout,/adminSignup,/activeDefaultAccount
        - id: payment-order-service
          uri: http://Paymentandorderservice-env.eba-mpa2bgig.us-east-1.elasticbeanstalk.com
          predicates:
            - Path=/payment/**,/order/**
