server:
  port: ${PORT:8080}

eureka:
  instance:
#    prefer-ip-address: true
    hostname: ${APPDOMAIN:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://127.0.0.1:8761/eureka/}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${REACT_APP_URL:"http://localhost:3000"}
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /cart/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: login-authentication
          uri: lb://login-authentication
          predicates:
            - Path=/login,/signup,/logout,/adminSignup,/activeDefaultAccount
        - id: payment-order-service
          uri: lb://payment-order-service
          predicates:
            - Path=/payment/**,/order/**
