server:
  port: 9002

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://sumesh_spring:sumesh123@cluster0.roe8a.mongodb.net/ecommerce?retryWrites=true&w=majority
#      host: localhost
#      port: 27017
#      database: ecommerce

eureka:
  instance:
    hostname: localhost

jwt:
  secret: "asdfghjkikjuhygfrd"
