server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    wait-time-in-ms-when-sync-empty: 0

#  instance:
#    hostname: ip-172-31-1-106.ap-south-1.compute.internal

  instance:
    hostname: localhost


