server:
  port: ${PORT:9001}

spring:
  application:
    name: login-authentication
  data:
    mongodb:
      uri: ${MONGODB_URL}

eureka:
  instance:
#    prefer-ip-address: true
    hostname: ${APPDOMAIN:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

jwt:
  secret: "asdfghjkikjuhygfrd"

account:
  email: ${ADMIN_EMAIL:"adminaccount1@gmail.com"}
  password: ${ADMIN_PASSWORD:"123456789"}

allowed:
  origin: ${REACT_APP_URL:http://localhost:3000}